---
title: "Stratified_State"
output: html_document
date: '2022-11-15'
---

--

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls()) 
```


```{r}
library(pacman) 
p_load("devtools", "dplyr", "scales", "ellipse", "ggplot2", "lazyeval", "igraph", "truncnorm", "ggraph", "reshape2", "knitr", "markdown", "stringr","readxl", "plyr","readr","data.table", "tidyr", "zoo", "lubridate", "ggpubr", "purrr", "forestplot", "grid", "forestploter", "broom")
setwd("C:/Users/cu888/Dropbox (Partners HealthCare)/Harvard/Projects/CEA_PrescriptionOpioid/PrescribingPolicies_Analysis/GeospatialAnalysis/Racial_Disparities")
```

#Data Preparation
```{r}
dat<-fread('Final sample_HD14DAYS_Dec14_1year.csv')

# Excluded PR from the analytical sample
dat1 = dat[state!="PR",c("PATIENT_ID","episode.start","episode.end","state","age","race","gender","last_MME","high_MME","previous_to_last2",
              "first_MME","total_days_high","classification","PAY_TYP_DESC")]

dat1$month_end = substr(dat1$episode.end,1,7)
table(dat1$month_end)

#  age>18; white hispanic, and black race
table(dat1$race)
dat2 = dat1[race %in% c("BLACK","WHITE", "HISPANIC"),]
nrow(dat2)
# 355523

#combine black and hispanic
#dat2$race[ dat2$race == "BLACK"] <- "other"
#dat2$race[ dat2$race == "HISPANIC"] <- "other"

table(dat2$age)
dat2 = dat2[!(age=="<18"),]
nrow(dat2)
# 354940 final analytical sample

dat2$year_start = as.numeric(substr(dat2$episode.start,1,4))-2014
#table(dat3$year.start)
dat2$year_end = as.numeric(substr(dat2$episode.end,1,4))-2014
#table(dat3$year.end)

# Re-categorizing variables
dat2[ , abrupt := fifelse(classification=="abrupt discontinue",1,0)]
#table(dat2$race_rev, dat2$abrupt, dat2$classification)

#table(dat2$state)


dat2[,race_rev := fifelse(race=="BLACK",1,
                          ifelse(race=="HISPANIC",2,0))]

dat2[,payment := fifelse(PAY_TYP_DESC=="MEDICAID", 1,
                         ifelse(PAY_TYP_DESC=="THIRD PARTY",3,
                                ifelse(PAY_TYP_DESC=="CASH",4,2)))]
# table(dat3$PAY_TYP_DESC,dat3$payment)

dat2[,firstMME := fifelse(first_MME<50, 0,
                         ifelse(first_MME>=50 & first_MME<90,1,
                                ifelse(first_MME>=90 & first_MME<120,2,
                                       ifelse(first_MME>=120 ,3,4))))]

dat2$abrupt = as.factor(dat2$abrupt)
dat2$race_rev = as.factor(dat2$race_rev)
dat2$payment = as.factor(dat2$payment)
dat2$firstMME = as.factor(dat2$firstMME)


fwrite(dat2, "Final sample_HD14DAYS_Dec14_1year_US.csv")


```

#Table for p-value by state and covariate (adjusted)
```{r}

dat<-fread("Final sample_HD14DAYS_Dec14_1year_US.csv")

  
dat$age = as.factor(dat$age)
dat$gender = as.factor(dat$gender)
dat$abrupt = as.factor(dat$abrupt)
dat$race_rev = as.factor(dat$race_rev)
dat$payment = as.factor(dat$payment)
dat$firstMME = as.factor(dat$firstMME)



result=glm(abrupt ~ race_rev+age+gender+payment+year_end+firstMME, 
                data = dat, family = "binomial")

COEFF=as.data.frame(summary(result)$coefficients)
OR=as.data.frame(exp(cbind("Odds ratio" = coef(result), confint.default(result, level = 0.95))))

out_coeff <-bind_cols(COEFF,OR)

fwrite(out_coeff,"regression_outcome_US_Dec22.csv", row.names = TRUE)
```

#non adjusted 
```{r}
 
dat<-fread("Final sample_HD14DAYS_Dec14_1year_US.csv")

  
dat$age = as.factor(dat$age)
dat$gender = as.factor(dat$gender)
dat$abrupt = as.factor(dat$abrupt)
dat$race_rev = as.factor(dat$race_rev)
dat$payment = as.factor(dat$payment)
dat$firstMME = as.factor(dat$firstMME)

#Bivariate glm

result=glm(abrupt ~ year_end, data=dat,family = "binomial")

COEFF=as.data.frame(summary(result)$coefficients)
OR=as.data.frame(exp(cbind("Odds ratio" = coef(result), confint.default(result, level = 0.95))))

out_coeff <-bind_cols(COEFF,OR)
print(out_coeff)

```

